"""add_finance_tables

Revision ID: e0d4b936e15a
Revises: 3feb2d83aedc
Create Date: 2026-07-25 14:13:23.217874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d4b936e15a'
down_revision: Union[str, None] = '3feb2d83aedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoices', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('balance_due', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('payment_status', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('invoice_id', sa.UUID(), nullable=True))
    op.add_column('purchase_orders', sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('purchase_orders', sa.Column('balance_due', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('purchase_orders', sa.Column('payment_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'payment_status')
    op.drop_column('purchase_orders', 'balance_due')
    op.drop_column('purchase_orders', 'paid_amount')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'invoice_id')
    op.drop_column('invoices', 'payment_status')
    op.drop_column('invoices', 'balance_due')
    op.drop_column('invoices', 'paid_amount')
    op.drop_column('invoices', 'due_date')
    op.drop_table('supplier_payments')
    # ### end Alembic commands ###
